name: jira-version-actions
on:
  push:
    paths:
      - '/env/prod.jira.releases.releasedate.properties'
      - '/payload/releases.json'
env:
  MAILUSER: ${{ secrets.MAIL_USER }}
  MAILPASS: ${{ secrets.MAIL_PASS }}
  JIRAUSER: ${{ secrets.JIRA_USER }}
  JIRAPASS: ${{ secrets.JIRA_PASS }}
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: Get changed files using separator
        id: changed-new-releases-properties
        uses: tj-actions/changed-files@v24
        with:
          files: /env/prod.jira.releases.releasedate.properties
      - name: Run step if releasedate.properties has changed
        if: steps.changed-new-releases-properties.outputs.any_changed == 'true'
        run: echo '/actions/server/createRequestedVersions.sh'
        shell: bash

      - name: Get changed files using separator
        id: changed-updated-releases-json
        uses: tj-actions/changed-files@v24
        with:
          files: /payload/releases.json
      - name: Run step if releases.json has changed
        if: steps.changed-updated-releases-json.outputs.any_changed == 'true'
        run: echo '/actions/server/updateChangedVersion.sh'
        shell: bash
