name: mail-merge-actions
on:
  push:
    paths:
      - '**/*'
env:
  MAILUSER: ${{ secrets.MAIL_USER }}
  MAILPASS: ${{ secrets.MAIL_PASS }}
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: check out this project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python & install mailmerge
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - run: pip install mailmerge
        shell: bash
      - run: mailmerge --no-dry-run --template templates/DeploymentSingleMarket.html --database 'Miles PROD SF1-NL Deployment Approval.csv' <<< $MAILPASS
        shell: bash
