name: mail-merge-actions
on:
  push:
    paths:
      - '**/*'
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: setup & install mailmerge
        run: |
          pip install mailmerge
