name: mail-merge-actions
on:
  push:
    paths:
      - '**/*'
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: setup & install python
        run: |
          apt install -y software-properties-common
          apt-get update -y; apt upgrade -y
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get update && apt-cache search python3.1
          apt-get install python3.11 -y
      - name: setup & install mailmerge
        run: |
          pip install mailmerge
