name: mail-merge-actions
on:
  push:
    paths:
      - '**/*'
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: setup & install python
        run: |
          sudo apt-get install python3.11 -y
      - name: setup & install mailmerge
        run: |
          sudo pip install mailmerge
