name: mail-merge-actions
on:
  push:
    paths:
      - '**/*'
env:
  MAILUSER: ${{ secrets.MAIL_USER }}
  MAILPASS: ${{ secrets.MAIL_PASS }}
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: check out this project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python & install mailmerge
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - run: pip install mailmerge
        shell: bash
      - name: Get changed files using separator
        id: changed-files-eol
        uses: tj-actions/changed-files@v24
        with:
          files: |
            **/*.csv
          files_ignore: |
            **/*.html
      - name: Use changed files as file name to figure system, template, market, database
        id: use-changed-files
        if: steps.changed-files-eol.outputs.any_changed == 'true'
        run: |
          echo "Run MailMerge with the changed files: "
          for file in "${{ steps.changed-files-eol.outputs.all_changed_files }}"; do
            printf "$file is the changed file found!\n";
            template=$(bash selectTemplate.sh "$file");
            echo "mailmerge --no-dry-run --template templates/$template --database '$file' <<< $MAILPASS"; 
            mailmerge --no-dry-run --template templates/$template --database "\'"$file"\'" <<< $MAILPASS;
          done
        shell: bash
